# Generated by Django 2.2.2 on 2019-07-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190727_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
