# Generated by Django 2.2.2 on 2019-08-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_print_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='cnt',
        ),
    ]
