# Generated by Django 2.2.2 on 2019-08-03 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_print_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='lecture',
        ),
        migrations.AddField(
            model_name='print',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='models.Schedule'),
            preserve_default=False,
        ),
    ]
