# Generated by Django 2.2.2 on 2019-08-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20190803_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
