# Generated by Django 2.2.2 on 2019-07-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_lecture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
