# Generated by Django 2.2.2 on 2019-08-06 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_schedule_req_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='req_print',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='req_print', to='models.Print'),
        ),
    ]
