# Generated by Django 2.2.2 on 2019-08-07 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_auto_20190806_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='print',
            name='alpha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=5000),
        ),
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('req_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_p', to='models.Print')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
