# Generated by Django 2.2.2 on 2019-08-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20190807_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print',
            old_name='price',
            new_name='delivery_price',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='alpha',
            new_name='print_price',
        ),
    ]
